reference: http://www.objc.io/issue-6/travis-ci.html
language: objective-c
osx_image: xcode8.2
xcode_sdk: iphonesimulator9.1
cache: bundler
before_install:
    - gem install xcpretty --no-rdoc --no-ri --no-document --quiet
script:
    - xcodebuild -project 'Example/Example.xcodeproj' -scheme Example -sdk iphonesimulator | xcpretty
